name: passat
description: A new weather app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.2+1
  http: ^0.12.2
  json_annotation: ^3.0.1
  flutter_svg: ^0.18.1

  cupertino_icons: ^0.1.3
  shimmer: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.1
  json_serializable: ^3.2.0

  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
